services:
  mysql:
    image: mysql:8.4
    container_name: mysql8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql

  # 分析専用コンテナ
  percona-toolkit:
    image: perconalab/percona-toolkit:latest
    container_name: percona-toolkit
    volumes:
      - ./mysql/logs:/logs:ro
      - ./reports:/reports
    depends_on:
      - mysql
    # 常時起動させない（分析時のみ起動）
    profiles:
      - analysis
    command: tail -f /dev/null

   # リアルタイムアラート監視
  slow-monitor:
    build: ./monitor
    container_name: slow-monitor
    env_file:
      - .env
    volumes:
      - ./mysql/logs:/logs:ro
    depends_on:
      - mysql
    restart: unless-stopped

  pmm-server:
    image: percona/pmm-server:3
    container_name: pmm-server
    # environment:
    #   PMM_WATCHTOWER_HOST: http://watchtower:8080
    #   PMM_WATCHTOWER_TOKEN: watchtower
    ports:
      - "8081:80"  # ポート変更
      - "443:8443"
    volumes:
      - pmm-data:/srv
    restart: unless-stopped

  # watchtower:
  #   image: percona/watchtower:latest
  #   container_name: watchtower
  #   restart: always
  #   environment:
  #     - WATCHTOWER_HTTP_API_TOKEN=watchtower
  #     - WATCHTOWER_HTTP_API_UPDATE=1
  #     - WATCHTOWER_POLL_INTERVAL=87600
  #     - WATCHTOWER_CLEANUP=true
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - pmm-server
  #     - mysql

volumes:
  mysql_data:
  pmm-data:
